/*
*Copyright (c) 2013 Thomas Falkenberg.
*All rights reserved. This program and the accompanying materials
*are made available under the terms of the GNU Public License v3.0
*which accompanies this distribution, and is available at
*http://www.gnu.org/licenses/gpl.html
*
*Contributors:
*    Thomas Falkenberg - initial API and implementation
*    Deutsche Telekom AG- Telekom Laboratories Darmstadt
*/

// Generated by CoffeeScript 1.3.3
/*global define
 */

define([ 'controllers/controllers', 'services/sharedScope' ], function(
		controllers) {
	'use strict';
	return controllers.controller('CallProtocol', [
			'$scope','sharedScope','$rootScope',
			function($scope, sharedScope,$rootScope) {
				$rootScope.Tab1="";
				$rootScope.Tab2="";
				$rootScope.Tab3="";
				$rootScope.Tab4="selected";
				
				$scope.sharedScope = sharedScope;
				

			} ]);
});
