/*
*Copyright (c) 2013 Thomas Falkenberg.
*All rights reserved. This program and the accompanying materials
*are made available under the terms of the GNU Public License v3.0
*which accompanies this distribution, and is available at
*http://www.gnu.org/licenses/gpl.html
*
*Contributors:
*    Thomas Falkenberg - initial API and implementation
*    Deutsche Telekom AG- Telekom Laboratories Darmstadt
*/

// Generated by CoffeeScript 1.3.3
/*global define
*/

define(['controllers/controllers', 'services/Contact','services/sharedScope'], function(controllers) {
  'use strict';
  return controllers.controller('Contact', [
    '$scope', 'Contact','sharedScope','$rootScope', function($scope, Contact,sharedScope,$rootScope) {
    	
		$scope.sharedScope=sharedScope;
		$scope.sharedScope.Contact=Contact;
		$rootScope.Tab1="";
		$rootScope.Tab2="";
		$rootScope.Tab3="selected";
		$rootScope.Tab4="";
		
		sharedScope.newContact("1061","Account","101@"+sharedScope.registration.domain);
		sharedScope.newContact("1061","Account","1061@"+sharedScope.registration.domain);
		sharedScope.newContact("2060","Account","200@"+sharedScope.registration.domain);
		sharedScope.newContact("2060","Account","2060@"+sharedScope.registration.domain);
    }
  ]);
});
