/*
*Copyright (c) 2013 Thomas Falkenberg.
*All rights reserved. This program and the accompanying materials
*are made available under the terms of the GNU Public License v3.0
*which accompanies this distribution, and is available at
*http://www.gnu.org/licenses/gpl.html
*
*Contributors:
*    Thomas Falkenberg - initial API and implementation
*    Deutsche Telekom AG- Telekom Laboratories Darmstadt
*/

// Generated by CoffeeScript 1.3.3
/*global define
*/

define(['controllers/controllers', 'services/SipConnection','services/sharedScope'], function(controllers) {
  'use strict';
  return controllers.controller('SipConnection', [
    '$scope', 'SipConnection','sharedScope', function($scope, SipConnection,sharedScope) {
    	
    	
    	$scope.sharedScope=sharedScope;
    	$scope.sharedScope.connection=new SipConnection();
    	$scope.sharedScope.connection.initialize();
    	$scope.sharedScope.connection.connect();
    	
    	
    	$scope.register=function(){
    		
    		$scope.sharedScope.connection.register();
    	};
    	$scope.check= function() {
    		try {
    			if($scope.sharedScope.createRegistration().state==$scope.sharedScope.REGISTERED
    				|| $scope.sharedScope.createRegistration().state==$scope.sharedScope.REGISTERING){
    	    		$scope.sharedScope.connection.register();
    			}
			} catch (e) {
				// TODO: handle exception
			}
			
		};
		window.onbeforeunload=$scope.check;
    	
    }
  ]);
});
