/*
*Copyright (c) 2013 Thomas Falkenberg.
*All rights reserved. This program and the accompanying materials
*are made available under the terms of the GNU Public License v3.0
*which accompanies this distribution, and is available at
*http://www.gnu.org/licenses/gpl.html
*
*Contributors:
*    Thomas Falkenberg - initial API and implementation
*    Deutsche Telekom AG- Telekom Laboratories Darmstadt
*/

// Generated by CoffeeScript 1.3.3
/*global define, describe, beforeEach, module, it, inject, expect
*/

define(['libs/angularMocks', 'services/Registration','services/sharedScope', 'services/SipConnection'], function() {
  'use strict';
  return describe('Registration service', function() {
    beforeEach(module('services'));
    

   
    
    it('should register', inject(['Registration','sharedScope','SipConnection', function(Registration,sharedScope,SipConnection) {
    	sharedScope.connection=new SipConnection();
    	sharedScope.connection.initialize();
    	sharedScope.connection.connect();
    	expect(sharedScope.Registration).toBeDefined();
    	expect(sharedScope.registration).not.toBeNull();
    	waitsFor(function() {
			return sharedScope.connection.socket.state==sharedScope.CONNECTED;
		}, "It took too long to connect to socket.", 5000);
    	runs(function() {
    	expect(sharedScope.connection.socket.state).toBe(sharedScope.CONNECTED);
    	sharedScope.connection.register();
    	});
    	
    	waitsFor(function() {
    		return sharedScope.registration.state==sharedScope.REGISTERED;
		}, "It took too long to register", 5000);
    	runs(function() {
        	expect(sharedScope.registration.state).toBe(sharedScope.REGISTERED);
        	sharedScope.connection.register();
        });
    	waitsFor(function() {
    		return sharedScope.registration.state==sharedScope.NOTREGISTERED;
		}, "It took too long to unregister", 5000);
    	runs(function() {
        	expect(sharedScope.registration.state).toBe(sharedScope.NOTREGISTERED);;
        });
     }
   ]));
    
    return it('Registration Service should be defined', inject([
      'Registration', function(Registration) {
        return expect(Registration).toBeDefined();
      }
    ]));
  });
});
